version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo:4.0
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
  mongoexpress:
    image: mongo-express:latest
    container_name: mongoexpress
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - 8081:8081

volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG